version: '3.3'

services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sakila
    ports:
      - "3306:3306"
  movies:
    image: "movies:latest"
    ports:
     - "8095:8095"

volumes:
    db_data: